micronaut:
  application:
    name: cargo-tracker
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  server:
    cors:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "vhieoafhbaqee1ze6f1ez5f1eafaef15e6af41ae6q"

rabbitmq:
  queues:
    cargoHandledQueue: cargo.handled
    misdirectedCargoQueue: cargo.misdirected
    deliveredCargoQueue: cargo.delivered
    handlingEventQueue: cargo.handling.event
    rejectedEventQueue: cargo.rejected.event
  uri: "amqp://guest:guest@localhost:5672"

datasources:
  default:
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
    jdbc-url: jdbc:mysql://localhost:3306/cargo
    username: root
    password: azeqsd

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    entity-scan:
      packages: org.johan.tracker.cargotracker.infrastructure.jpa
